// GENERATED by the iDos Games platform when this project was created.
// Do not edit: this is the project's identity — which Title's data the built game reads
// and writes. The AI editor is denied write access to this path on purpose.

/** Canonical (production) Title id. The DEV title is derived as `{id}-DEV`. */
export const IDOS_TITLE_ID = "1ZPS8DLV";

/** Build key for this title, if the title enforces one. */
export const IDOS_BUILD_KEY = "";

/** Environment this artifact defaults to. Web builds may override it; a packaged mobile build cannot. */
export const IDOS_DEFAULT_ENV: "prod" | "dev" = "prod";

/** Whether this title was created as web3. Drives which providers the login screen offers. */
export const IDOS_WEB3 = false;

/** NetworkID the wallet login challenge is issued for. Empty on web2 titles. */
export const IDOS_WEB3_NETWORK_ID = "";

/** WalletConnect Cloud / Reown project id — enables mobile wallet login (WalletConnect QR/deep-link).
 *  Baked here (not read at runtime) because the login screen needs it before there is a session.
 *  Empty means only browser-extension wallets; set it in the title's blockchain config. */
export const IDOS_WEB3_WALLETCONNECT_PROJECT_ID = "";
